<a href="https://colab.research.google.com/github/Rahuljha-cell/Leetcode-Practice/blob/main/Introduction_to_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
demo = [10, 20, 30]
print(demo)
np.array(demo)

[10, 20, 30]


array([10, 20, 30])

In [ ]:
demo2 = [10, 20, "xyz"]
np.array(demo2)

array(['10', '20', 'xyz'], dtype='<U21')

In [ ]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [ ]:
np.zeros(5, int)

array([0, 0, 0, 0, 0])

In [ ]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [ ]:
np.ones(5, int)

array([1, 1, 1, 1, 1])

In [ ]:
x = np.zeros(10)
x.dtype

dtype('float64')

In [ ]:
x = np.zeros(10, int)
x.dtype

dtype('int64')

In [ ]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
x5 = np.ones(5)
print(x5)

[1. 1. 1. 1. 1.]


In [ ]:
x5 = np.ones(5)
x5[3] = "10"
x5[2] = "2"
print(x5)

[ 1.  1.  2. 10.  1.]


In [ ]:
new_array = np.zeros((3,4,5))
print(new_array)
new_array[0][1][2]
print(new_array[0][1])
new_array[2]

[[[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]]
[0. 0. 0. 0. 0.]


array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [ ]:
new_array.shape

(3, 4, 5)

In [ ]:
a = np.zeros(5)
print(a)
a[2:5]

[0. 0. 0. 0. 0.]


array([0., 0., 0.])

In [ ]:
twoD_array = np.array([[1,2,3], [4,5,6], [7,8,9]])
print(twoD_array)

print(twoD_array[1][2])
print(twoD_array[1:3])

print(twoD_array[:, 1])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
6
[[4 5 6]
 [7 8 9]]
[2 5 8]


In [ ]:
new_twoD_array = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
print(new_twoD_array)
new_twoD_array[1:3,0]

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


array([4, 7])

In [ ]:
new_twoD_array[1:3, 0:2]

array([[4, 5],
       [7, 8]])