<a href="https://colab.research.google.com/github/Rahuljha-cell/Leetcode-Practice/blob/main/Numpy_2_Operations.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import math as m

In [5]:
x = [1, 2, 3]
y = [4, 5, 6]
x  = x + 10
print(x)

TypeError: can only concatenate list (not "int") to list

In [8]:
x = np.array([1,2,3])
y = np.array([3,5,6])
print(x+y)
x = x + 10
print(x)

print(x + y)

[4 7 9]
[11 12 13]
[14 17 19]


In [9]:
z = np.array([100, 200, 300, 400])
print(y + z)

ValueError: operands could not be broadcast together with shapes (3,) (4,) 

In [10]:
print(x*2)
print(x*y)
print(x**3)

[22 24 26]
[33 60 78]
[1331 1728 2197]


In [11]:
print(x.mean())
print(x.sum())

12.0
36


In [12]:
p1 = np.array([2,2,2])
p2 = np.array([1,1,1])

val = ((p1-p2)**2).sum()
print(val)

# val2 = val.sum()
# print(val)

m.sqrt(val)



3


1.7320508075688772

In [14]:
pts = np.array([4, 5, 6, 7])

value1 = ((pts - pts.mean())**2).sum()
print(value1)
m.sqrt(value1)

5.0


2.23606797749979

In [15]:
m1 = np.array([1,2,3])
m2 = np.array([4,5,6])
print(m1.dot(m2))

32
